
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  objectEnumValues,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/wasm-engine-edge.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.1
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.1",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}





/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.MessagesScalarFieldEnum = {
  id: 'id',
  chatId: 'chatId',
  linkId: 'linkId',
  message: 'message',
  date: 'date'
};

exports.Prisma.ChatsScalarFieldEnum = {
  chatId: 'chatId',
  hostId: 'hostId',
  name: 'name',
  lastAccessed: 'lastAccessed'
};

exports.Prisma.UserScalarFieldEnum = {
  userId: 'userId',
  linkId: 'linkId',
  username: 'username'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  messages: 'messages',
  chats: 'chats',
  user: 'user'
};
/**
 * Create the Client
 */
const config = {
  "generator": {
    "name": "chat",
    "provider": {
      "fromEnvVar": null,
      "value": "prisma-client-js"
    },
    "output": {
      "value": "/home/fre007/Desktop/temp/Transcendence/backend/database/chat/database/generate/chat",
      "fromEnvVar": null
    },
    "config": {
      "engineType": "library"
    },
    "binaryTargets": [
      {
        "fromEnvVar": null,
        "value": "debian-openssl-3.0.x",
        "native": true
      }
    ],
    "previewFeatures": [],
    "sourceFilePath": "/home/fre007/Desktop/temp/Transcendence/backend/database/chat/database/chat.prisma",
    "isCustomOutput": true
  },
  "relativeEnvPaths": {
    "rootEnvPath": null
  },
  "relativePath": "../..",
  "clientVersion": "6.19.1",
  "engineVersion": "c2990dca591cba766e3b7ef5d9e8a84796e47ab7",
  "datasourceNames": [
    "dbchat"
  ],
  "activeProvider": "sqlite",
  "inlineDatasources": {
    "dbchat": {
      "url": {
        "fromEnvVar": null,
        "value": "file:./chat.db"
      }
    }
  },
  "inlineSchema": "// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator chat {\n  provider = \"prisma-client-js\"\n  output   = \"./generate/chat\"\n}\n\ndatasource dbchat {\n  provider = \"sqlite\"\n  url      = \"file:./chat.db\"\n}\n\nmodel messages {\n  id      Int      @id @default(autoincrement())\n  chatId  Int\n  linkId  Int\n  chat    chats    @relation(fields: [chatId], references: [chatId], onDelete: Cascade)\n  user    user     @relation(fields: [linkId], references: [linkId], onDelete: Cascade)\n  message String\n  date    DateTime @default(now())\n}\n\nmodel chats {\n  chatId       Int        @id @default(autoincrement())\n  hostId       Int\n  host         user       @relation(\"host\", fields: [hostId], references: [linkId], onDelete: Cascade)\n  users        user[]     @relation(\"members\")\n  messages     messages[]\n  name         String\n  lastAccessed DateTime?  @updatedAt\n}\n\nmodel user {\n  userId       Int        @id @default(autoincrement())\n  linkId       Int        @unique\n  messages     messages[]\n  chatHost     chats[]    @relation(\"host\")\n  members      chats[]    @relation(\"members\")\n  blockedUsers user[]     @relation(\"BlockedUsers\")\n  blockedBy    user[]     @relation(\"BlockedUsers\")\n  username     String?    @unique\n}\n",
  "inlineSchemaHash": "75088fcea333097a02586ecbceb335bfdbdcba7c90c552f042f2a3a9d5cc4759",
  "copyEngine": true
}
config.dirname = '/'

config.runtimeDataModel = JSON.parse("{\"models\":{\"messages\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"chatId\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"linkId\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"chat\",\"kind\":\"object\",\"type\":\"chats\",\"relationName\":\"chatsTomessages\"},{\"name\":\"user\",\"kind\":\"object\",\"type\":\"user\",\"relationName\":\"messagesTouser\"},{\"name\":\"message\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"date\",\"kind\":\"scalar\",\"type\":\"DateTime\"}],\"dbName\":null},\"chats\":{\"fields\":[{\"name\":\"chatId\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"hostId\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"host\",\"kind\":\"object\",\"type\":\"user\",\"relationName\":\"host\"},{\"name\":\"users\",\"kind\":\"object\",\"type\":\"user\",\"relationName\":\"members\"},{\"name\":\"messages\",\"kind\":\"object\",\"type\":\"messages\",\"relationName\":\"chatsTomessages\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"lastAccessed\",\"kind\":\"scalar\",\"type\":\"DateTime\"}],\"dbName\":null},\"user\":{\"fields\":[{\"name\":\"userId\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"linkId\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"messages\",\"kind\":\"object\",\"type\":\"messages\",\"relationName\":\"messagesTouser\"},{\"name\":\"chatHost\",\"kind\":\"object\",\"type\":\"chats\",\"relationName\":\"host\"},{\"name\":\"members\",\"kind\":\"object\",\"type\":\"chats\",\"relationName\":\"members\"},{\"name\":\"blockedUsers\",\"kind\":\"object\",\"type\":\"user\",\"relationName\":\"BlockedUsers\"},{\"name\":\"blockedBy\",\"kind\":\"object\",\"type\":\"user\",\"relationName\":\"BlockedUsers\"},{\"name\":\"username\",\"kind\":\"scalar\",\"type\":\"String\"}],\"dbName\":null}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.engineWasm = {
  getRuntime: async () => require('./query_engine_bg.js'),
  getQueryEngineWasmModule: async () => {
    const loader = (await import('#wasm-engine-loader')).default
    const engine = (await loader).default
    return engine
  }
}
config.compilerWasm = undefined

config.injectableEdgeEnv = () => ({
  parsed: {}
})

if (typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined) {
  Debug.enable(typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined)
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)

